import { createRequire } from 'module';
const require = createRequire(import.meta.url);
const frontrunnerTrips = require('../src/data/frontrunner-trips.json');

export const agencies = [
  {
    id: 'amtrak', name: 'Amtrak', color: '#1a73e8',
    logo: '/logos/amtrak.png',
    fetcher: 'amtrak',
  },
  {
    id: 'mbta', name: 'MBTA', color: '#80276C',
    logo: '/logos/mbta.png',
    fetcher: 'mbta',
    apiKey: process.env.MBTA_API_KEY,
  },
  {
    id: 'caltrain', name: 'Caltrain', color: '#e21836',
    logo: '/logos/caltrain.png',
    fetcher: 'json511', code: 'CT',
    apiKey: process.env.API_KEY_511,
  },
  {
    id: 'ace', name: 'ACE', color: '#1b4b8a',
    logo: '/logos/ace.png',
    fetcher: 'json511', code: 'CE',
    apiKey: process.env.API_KEY_511,
  },
  {
    id: 'smart', name: 'SMART', color: '#009DA5',
    logo: '/logos/smart.png',
    fetcher: 'json511', code: 'SA',
    apiKey: process.env.API_KEY_511,
  },
  {
    id: 'metrolink', name: 'Metrolink', color: '#F26522',
    logo: '/logos/metrolink.png',
    fetcher: 'gtfsrt',
    url: 'https://metrolink-gtfsrt.gbsdigital.us/feed/gtfsrt-vehicles',
    headers: { 'x-api-key': process.env.METROLINK_API_KEY },
  },
  {
    id: 'marc', name: 'MARC', color: '#004B87',
    logo: '/logos/marc.png',
    fetcher: 'gtfsrt',
    url: 'https://mdotmta-gtfs-rt.s3.amazonaws.com/MARC+RT/marc-vp.pb',
  },
  {
    id: 'vre', name: 'VRE', color: '#DA291C',
    logo: '/logos/vre.png',
    fetcher: 'gtfsrt',
    url: 'https://gtfs.vre.org/containercdngtfsupload/VehiclePositionFeed',
  },
  {
    id: 'septa', name: 'SEPTA', color: '#1C4D8C',
    logo: '/logos/septa.png',
    fetcher: 'gtfsrt',
    url: 'https://www3.septa.org/gtfsrt/septarail-pa-us/Vehicle/rtVehiclePosition.pb',
  },
  {
    id: 'brightline', name: 'Brightline', color: '#F2E205',
    logo: '/logos/brightline.png',
    fetcher: 'gtfsrt',
    url: 'http://feed.gobrightline.com/position_updates.pb',
  },
  {
    id: 'rtd', name: 'RTD A/B', color: '#57C1E9',
    logo: '/logos/rtd.png',
    fetcher: 'gtfsrt',
    url: 'https://www.rtd-denver.com/files/gtfs-rt/VehiclePosition.pb',
    filterRouteIds: ['A', '113B'],
  },
  {
    id: 'frontrunner', name: 'FrontRunner', color: '#c227b9',
    logo: '/logos/frontrunner.png',
    fetcher: 'gtfsrt',
    url: 'https://apps.rideuta.com/tms/gtfs/Vehicle',
    filterTripIds: frontrunnerTrips,
  },
  {
    id: 'wegostar', name: 'WeGo Star', color: '#001E61',
    logo: '/logos/wegostar.png',
    fetcher: 'gtfsrt',
    url: 'http://transitdata.nashvillemta.org/TMGTFSRealTimeWebService/vehicle/vehiclepositions.pb',
    filterRouteIds: ['90'],
  },
  {
    id: 'nicd', name: 'NICD', color: '#005DAA',
    logo: '/logos/nicd.png',
    fetcher: 'gtfsrt',
    url: 'https://s3.amazonaws.com/etatransit.gtfs/southshore.etaspot.net/position_updates.pb',
  },
  {
    id: 'northstar', name: 'Northstar', color: '#009BDA',
    logo: '/logos/northstar.png',
    fetcher: 'gtfsrt',
    url: 'https://svc.metrotransit.org/mtgtfs/vehiclepositions.pb',
    filterRouteIds: ['888'],
  },
  {
    id: 'capmetro', name: 'MetroRail', color: '#E3242B',
    logo: '/logos/capmetro.png',
    fetcher: 'gtfsrt',
    url: 'https://data.texas.gov/download/eiei-9rpf/application%2Foctet-stream',
    filterRouteIds: ['550'],
  },
  {
    id: 'soundtransit', name: 'Sound Transit', color: '#005DAA',
    logo: '/logos/soundtransit.png',
    fetcher: 'gtfsrt',
    url: 'http://api.pugetsound.onebusaway.org/api/gtfs_realtime/vehicle-positions-for-agency/40.pb?key=' + process.env.SOUNDTRANSIT_API_KEY,
    filterRouteIds: ['100479', '2LINE', 'TLINE'],
  },
  {
    id: 'metra', name: 'Metra', color: '#00205B',
    logo: '/logos/metra.jpg',
    fetcher: 'gtfsrt',
    url: 'https://gtfspublic.metrarr.com/gtfs/public/positions',
    headers: { 'Authorization': 'Bearer ' + process.env.METRA_API_TOKEN },
  },
  {
    id: 'exo', name: 'Exo', color: '#00A6A2',
    logo: '/logos/exo.png',
    fetcher: 'gtfsrt',
    url: 'https://opendata.exo.quebec/ServiceGTFSR/VehiclePosition.pb?$agency=TRAINS&token=' + process.env.EXO_API_TOKEN,
  },
  {
    id: 'go', name: 'GO Transit', color: '#3D8B37',
    logo: '/logos/go.svg',
    fetcher: 'gtfsrt',
    url: 'https://api.openmetrolinx.com/OpenDataAPI/api/V1/Gtfs/Feed/VehiclePosition?key=' + process.env.METROLINX_API_KEY,
    headers: { 'Accept': 'application/x-protobuf' },
    filterRouteIdSuffixes: ['LW', 'LE', 'BR', 'ST', 'GT', 'MI', 'RH'],
  },
  {
    id: 'njtransit', name: 'NJ Transit', color: '#003DA5',
    logo: '/logos/njtransit.png',
    fetcher: 'njtransit',
    username: process.env.NJT_USERNAME,
    password: process.env.NJT_PASSWORD,
  },
];
